/*
 * rcd_system.c -- see rcd_system.h
 */

#include "rcd_system.h"

#include <rss_common.h>

#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>

#define PATH_TZ	      RCD_SYSCONF_DIR "/TZ"
#define PATH_TIMEZONE RCD_SYSCONF_DIR "/timezone"
#define PATH_NTP      RCD_SYSCONF_DIR "/ntp.conf"
#define PATH_NTPD     RCD_SYSCONF_DIR "/init.d/S49ntpd"
#define PATH_HOSTNAME RCD_SYSCONF_DIR "/hostname"
#define PATH_HOSTS    RCD_SYSCONF_DIR "/hosts"
#define PATH_MDNSD    RCD_SYSCONF_DIR "/init.d/S50mdnsd"

/*
 * Names are what an operator picks; the POSIX string at the same index is what
 * musl parses. The DST rules are part of the string because there is no
 * zoneinfo database on the camera to look them up in.
 *
 * GENERATED by rcd/gen_timezones.py from the build host's tzdata, and every
 * entry verified by handing it to the C library and comparing a year of
 * offsets against zoneinfo. Do not hand-edit: regenerate.
 *
 * Two arrays rather than an array of pairs, because the names are also the
 * `choices` of the timezone key: the list the schema offers and the list `set`
 * accepts are then the same object and cannot drift. They are walked in
 * parallel, so a test asserts they are the same length.
 *
 * Two limitations, both inherent to describing a zone with one repeating rule:
 *
 *   - A zone that *changes* its rules is described by the rule in force before
 *     the change, so it is right today and wrong afterwards. tzdata 2026b has
 *     America/Vancouver dropping DST permanently on 2026-11-01; re-running the
 *     generator after that date is what fixes it.
 *   - Four zones are absent because no repeating rule can express them:
 *     Africa/Casablanca and Africa/El_Aaiun shift around Ramadan, and
 *     Asia/Gaza and Asia/Hebron are set irregularly.
 *
 * So this table ages, and a tzdata bump is the trigger to regenerate it.
 */
const char *const rcd_zone_names[] = {
	"UTC",
	"Africa/Abidjan",
	"Africa/Algiers",
	"Africa/Bissau",
	"Africa/Cairo",
	"Africa/Ceuta",
	"Africa/Johannesburg",
	"Africa/Juba",
	"Africa/Khartoum",
	"Africa/Lagos",
	"Africa/Maputo",
	"Africa/Monrovia",
	"Africa/Nairobi",
	"Africa/Ndjamena",
	"Africa/Sao_Tome",
	"Africa/Tripoli",
	"Africa/Tunis",
	"Africa/Windhoek",
	"America/Adak",
	"America/Anchorage",
	"America/Araguaina",
	"America/Argentina/Buenos_Aires",
	"America/Argentina/Catamarca",
	"America/Argentina/Cordoba",
	"America/Argentina/Jujuy",
	"America/Argentina/La_Rioja",
	"America/Argentina/Mendoza",
	"America/Argentina/Rio_Gallegos",
	"America/Argentina/Salta",
	"America/Argentina/San_Juan",
	"America/Argentina/San_Luis",
	"America/Argentina/Tucuman",
	"America/Argentina/Ushuaia",
	"America/Asuncion",
	"America/Bahia",
	"America/Bahia_Banderas",
	"America/Barbados",
	"America/Belem",
	"America/Belize",
	"America/Boa_Vista",
	"America/Bogota",
	"America/Boise",
	"America/Cambridge_Bay",
	"America/Campo_Grande",
	"America/Cancun",
	"America/Caracas",
	"America/Cayenne",
	"America/Chicago",
	"America/Chihuahua",
	"America/Ciudad_Juarez",
	"America/Costa_Rica",
	"America/Coyhaique",
	"America/Cuiaba",
	"America/Danmarkshavn",
	"America/Dawson",
	"America/Dawson_Creek",
	"America/Denver",
	"America/Detroit",
	"America/Edmonton",
	"America/Eirunepe",
	"America/El_Salvador",
	"America/Fort_Nelson",
	"America/Fortaleza",
	"America/Glace_Bay",
	"America/Goose_Bay",
	"America/Grand_Turk",
	"America/Guatemala",
	"America/Guayaquil",
	"America/Guyana",
	"America/Halifax",
	"America/Havana",
	"America/Hermosillo",
	"America/Indiana/Indianapolis",
	"America/Indiana/Knox",
	"America/Indiana/Marengo",
	"America/Indiana/Petersburg",
	"America/Indiana/Tell_City",
	"America/Indiana/Vevay",
	"America/Indiana/Vincennes",
	"America/Indiana/Winamac",
	"America/Inuvik",
	"America/Iqaluit",
	"America/Jamaica",
	"America/Juneau",
	"America/Kentucky/Louisville",
	"America/Kentucky/Monticello",
	"America/La_Paz",
	"America/Lima",
	"America/Los_Angeles",
	"America/Maceio",
	"America/Managua",
	"America/Manaus",
	"America/Martinique",
	"America/Matamoros",
	"America/Mazatlan",
	"America/Menominee",
	"America/Merida",
	"America/Metlakatla",
	"America/Mexico_City",
	"America/Miquelon",
	"America/Moncton",
	"America/Monterrey",
	"America/Montevideo",
	"America/New_York",
	"America/Nome",
	"America/Noronha",
	"America/North_Dakota/Beulah",
	"America/North_Dakota/Center",
	"America/North_Dakota/New_Salem",
	"America/Nuuk",
	"America/Ojinaga",
	"America/Panama",
	"America/Paramaribo",
	"America/Phoenix",
	"America/Port-au-Prince",
	"America/Porto_Velho",
	"America/Puerto_Rico",
	"America/Punta_Arenas",
	"America/Rankin_Inlet",
	"America/Recife",
	"America/Regina",
	"America/Resolute",
	"America/Rio_Branco",
	"America/Santarem",
	"America/Santiago",
	"America/Santo_Domingo",
	"America/Sao_Paulo",
	"America/Scoresbysund",
	"America/Sitka",
	"America/St_Johns",
	"America/Swift_Current",
	"America/Tegucigalpa",
	"America/Thule",
	"America/Tijuana",
	"America/Toronto",
	"America/Vancouver",
	"America/Whitehorse",
	"America/Winnipeg",
	"America/Yakutat",
	"Antarctica/Casey",
	"Antarctica/Davis",
	"Antarctica/Macquarie",
	"Antarctica/Mawson",
	"Antarctica/Palmer",
	"Antarctica/Rothera",
	"Antarctica/Troll",
	"Antarctica/Vostok",
	"Asia/Almaty",
	"Asia/Amman",
	"Asia/Anadyr",
	"Asia/Aqtau",
	"Asia/Aqtobe",
	"Asia/Ashgabat",
	"Asia/Atyrau",
	"Asia/Baghdad",
	"Asia/Baku",
	"Asia/Bangkok",
	"Asia/Barnaul",
	"Asia/Beirut",
	"Asia/Bishkek",
	"Asia/Chita",
	"Asia/Colombo",
	"Asia/Damascus",
	"Asia/Dhaka",
	"Asia/Dili",
	"Asia/Dubai",
	"Asia/Dushanbe",
	"Asia/Famagusta",
	"Asia/Ho_Chi_Minh",
	"Asia/Hong_Kong",
	"Asia/Hovd",
	"Asia/Irkutsk",
	"Asia/Jakarta",
	"Asia/Jayapura",
	"Asia/Jerusalem",
	"Asia/Kabul",
	"Asia/Kamchatka",
	"Asia/Karachi",
	"Asia/Kathmandu",
	"Asia/Khandyga",
	"Asia/Kolkata",
	"Asia/Krasnoyarsk",
	"Asia/Kuching",
	"Asia/Macau",
	"Asia/Magadan",
	"Asia/Makassar",
	"Asia/Manila",
	"Asia/Nicosia",
	"Asia/Novokuznetsk",
	"Asia/Novosibirsk",
	"Asia/Omsk",
	"Asia/Oral",
	"Asia/Pontianak",
	"Asia/Pyongyang",
	"Asia/Qatar",
	"Asia/Qostanay",
	"Asia/Qyzylorda",
	"Asia/Riyadh",
	"Asia/Sakhalin",
	"Asia/Samarkand",
	"Asia/Seoul",
	"Asia/Shanghai",
	"Asia/Singapore",
	"Asia/Srednekolymsk",
	"Asia/Taipei",
	"Asia/Tashkent",
	"Asia/Tbilisi",
	"Asia/Tehran",
	"Asia/Thimphu",
	"Asia/Tokyo",
	"Asia/Tomsk",
	"Asia/Ulaanbaatar",
	"Asia/Urumqi",
	"Asia/Ust-Nera",
	"Asia/Vladivostok",
	"Asia/Yakutsk",
	"Asia/Yangon",
	"Asia/Yekaterinburg",
	"Asia/Yerevan",
	"Atlantic/Azores",
	"Atlantic/Bermuda",
	"Atlantic/Canary",
	"Atlantic/Cape_Verde",
	"Atlantic/Faroe",
	"Atlantic/Madeira",
	"Atlantic/South_Georgia",
	"Atlantic/Stanley",
	"Australia/Adelaide",
	"Australia/Brisbane",
	"Australia/Broken_Hill",
	"Australia/Darwin",
	"Australia/Eucla",
	"Australia/Hobart",
	"Australia/Lindeman",
	"Australia/Lord_Howe",
	"Australia/Melbourne",
	"Australia/Perth",
	"Australia/Sydney",
	"Europe/Andorra",
	"Europe/Astrakhan",
	"Europe/Athens",
	"Europe/Belgrade",
	"Europe/Berlin",
	"Europe/Brussels",
	"Europe/Bucharest",
	"Europe/Budapest",
	"Europe/Chisinau",
	"Europe/Dublin",
	"Europe/Gibraltar",
	"Europe/Helsinki",
	"Europe/Istanbul",
	"Europe/Kaliningrad",
	"Europe/Kirov",
	"Europe/Kyiv",
	"Europe/Lisbon",
	"Europe/London",
	"Europe/Madrid",
	"Europe/Malta",
	"Europe/Minsk",
	"Europe/Moscow",
	"Europe/Paris",
	"Europe/Prague",
	"Europe/Riga",
	"Europe/Rome",
	"Europe/Samara",
	"Europe/Saratov",
	"Europe/Simferopol",
	"Europe/Sofia",
	"Europe/Tallinn",
	"Europe/Tirane",
	"Europe/Ulyanovsk",
	"Europe/Vienna",
	"Europe/Vilnius",
	"Europe/Volgograd",
	"Europe/Warsaw",
	"Europe/Zurich",
	"Indian/Chagos",
	"Indian/Maldives",
	"Indian/Mauritius",
	"Pacific/Apia",
	"Pacific/Auckland",
	"Pacific/Bougainville",
	"Pacific/Chatham",
	"Pacific/Easter",
	"Pacific/Efate",
	"Pacific/Fakaofo",
	"Pacific/Fiji",
	"Pacific/Galapagos",
	"Pacific/Gambier",
	"Pacific/Guadalcanal",
	"Pacific/Guam",
	"Pacific/Honolulu",
	"Pacific/Kanton",
	"Pacific/Kiritimati",
	"Pacific/Kosrae",
	"Pacific/Kwajalein",
	"Pacific/Marquesas",
	"Pacific/Nauru",
	"Pacific/Niue",
	"Pacific/Norfolk",
	"Pacific/Noumea",
	"Pacific/Pago_Pago",
	"Pacific/Palau",
	"Pacific/Pitcairn",
	"Pacific/Port_Moresby",
	"Pacific/Rarotonga",
	"Pacific/Tahiti",
	"Pacific/Tarawa",
	"Pacific/Tongatapu",
	NULL,
};

static const char *const zone_posix[] = {
	"UTC0",
	"GMT0",
	"CET-1",
	"GMT0",
	"EET-2EEST,M4.5.5/0,M10.5.5/0",
	"CET-1CEST,M3.5.0,M10.5.0/3",
	"SAST-2",
	"CAT-2",
	"CAT-2",
	"WAT-1",
	"CAT-2",
	"GMT0",
	"EAT-3",
	"WAT-1",
	"GMT0",
	"EET-2",
	"CET-1",
	"CAT-2",
	"HST10HDT,M3.2.0,M11.1.0",
	"AKST9AKDT,M3.2.0,M11.1.0",
	"<-03>3",
	"<-03>3",
	"<-03>3",
	"<-03>3",
	"<-03>3",
	"<-03>3",
	"<-03>3",
	"<-03>3",
	"<-03>3",
	"<-03>3",
	"<-03>3",
	"<-03>3",
	"<-03>3",
	"<-03>3",
	"<-03>3",
	"CST6",
	"AST4",
	"<-03>3",
	"CST6",
	"<-04>4",
	"<-05>5",
	"MST7MDT,M3.2.0,M11.1.0",
	"MST7MDT,M3.2.0,M11.1.0",
	"<-04>4",
	"EST5",
	"<-04>4",
	"<-03>3",
	"CST6CDT,M3.2.0,M11.1.0",
	"CST6",
	"MST7MDT,M3.2.0,M11.1.0",
	"CST6",
	"<-03>3",
	"<-04>4",
	"GMT0",
	"MST7",
	"MST7",
	"MST7MDT,M3.2.0,M11.1.0",
	"EST5EDT,M3.2.0,M11.1.0",
	"MST7MDT,M3.2.0,M11.1.0",
	"<-05>5",
	"CST6",
	"MST7",
	"<-03>3",
	"AST4ADT,M3.2.0,M11.1.0",
	"AST4ADT,M3.2.0,M11.1.0",
	"EST5EDT,M3.2.0,M11.1.0",
	"CST6",
	"<-05>5",
	"<-04>4",
	"AST4ADT,M3.2.0,M11.1.0",
	"CST5CDT,M3.2.0/0,M11.1.0/1",
	"MST7",
	"EST5EDT,M3.2.0,M11.1.0",
	"CST6CDT,M3.2.0,M11.1.0",
	"EST5EDT,M3.2.0,M11.1.0",
	"EST5EDT,M3.2.0,M11.1.0",
	"CST6CDT,M3.2.0,M11.1.0",
	"EST5EDT,M3.2.0,M11.1.0",
	"EST5EDT,M3.2.0,M11.1.0",
	"EST5EDT,M3.2.0,M11.1.0",
	"MST7MDT,M3.2.0,M11.1.0",
	"EST5EDT,M3.2.0,M11.1.0",
	"EST5",
	"AKST9AKDT,M3.2.0,M11.1.0",
	"EST5EDT,M3.2.0,M11.1.0",
	"EST5EDT,M3.2.0,M11.1.0",
	"<-04>4",
	"<-05>5",
	"PST8PDT,M3.2.0,M11.1.0",
	"<-03>3",
	"CST6",
	"<-04>4",
	"AST4",
	"CST6CDT,M3.2.0,M11.1.0",
	"MST7",
	"CST6CDT,M3.2.0,M11.1.0",
	"CST6",
	"AKST9AKDT,M3.2.0,M11.1.0",
	"CST6",
	"<-03>3<-02>,M3.2.0,M11.1.0",
	"AST4ADT,M3.2.0,M11.1.0",
	"CST6",
	"<-03>3",
	"EST5EDT,M3.2.0,M11.1.0",
	"AKST9AKDT,M3.2.0,M11.1.0",
	"<-02>2",
	"CST6CDT,M3.2.0,M11.1.0",
	"CST6CDT,M3.2.0,M11.1.0",
	"CST6CDT,M3.2.0,M11.1.0",
	"<-02>2<-01>,M3.5.6/23,M10.5.0/0",
	"CST6CDT,M3.2.0,M11.1.0",
	"EST5",
	"<-03>3",
	"MST7",
	"EST5EDT,M3.2.0,M11.1.0",
	"<-04>4",
	"AST4",
	"<-03>3",
	"CST6CDT,M3.2.0,M11.1.0",
	"<-03>3",
	"CST6",
	"CST6CDT,M3.2.0,M11.1.0",
	"<-05>5",
	"<-03>3",
	"<-04>4<-03>,M9.1.0/0,M4.1.0/0",
	"AST4",
	"<-03>3",
	"<-02>2<-01>,M3.5.6/23,M10.5.0/0",
	"AKST9AKDT,M3.2.0,M11.1.0",
	"NST3:30NDT,M3.2.0,M11.1.0",
	"CST6",
	"CST6",
	"AST4ADT,M3.2.0,M11.1.0",
	"PST8PDT,M3.2.0,M11.1.0",
	"EST5EDT,M3.2.0,M11.1.0",
	"PST8PDT,M3.2.0,M11.1.0",
	"MST7",
	"CST6CDT,M3.2.0,M11.1.0",
	"AKST9AKDT,M3.2.0,M11.1.0",
	"<+08>-8",
	"<+07>-7",
	"AEST-10AEDT,M10.1.0,M4.1.0/3",
	"<+05>-5",
	"<-03>3",
	"<-03>3",
	"<+00>0<+02>-2,M3.5.0/1,M10.5.0/3",
	"<+05>-5",
	"<+05>-5",
	"<+03>-3",
	"<+12>-12",
	"<+05>-5",
	"<+05>-5",
	"<+05>-5",
	"<+05>-5",
	"<+03>-3",
	"<+04>-4",
	"<+07>-7",
	"<+07>-7",
	"EET-2EEST,M3.5.0/0,M10.5.0/0",
	"<+06>-6",
	"<+09>-9",
	"<+0530>-5:30",
	"<+03>-3",
	"<+06>-6",
	"<+09>-9",
	"<+04>-4",
	"<+05>-5",
	"EET-2EEST,M3.5.0/3,M10.5.0/4",
	"<+07>-7",
	"HKT-8",
	"<+07>-7",
	"<+08>-8",
	"WIB-7",
	"WIT-9",
	"IST-2IDT,M3.5.5,M10.5.0",
	"<+0430>-4:30",
	"<+12>-12",
	"PKT-5",
	"<+0545>-5:45",
	"<+09>-9",
	"IST-5:30",
	"<+07>-7",
	"<+08>-8",
	"CST-8",
	"<+11>-11",
	"WITA-8",
	"PST-8",
	"EET-2EEST,M3.5.0/3,M10.5.0/4",
	"<+07>-7",
	"<+07>-7",
	"<+06>-6",
	"<+05>-5",
	"WIB-7",
	"KST-9",
	"<+03>-3",
	"<+05>-5",
	"<+05>-5",
	"<+03>-3",
	"<+11>-11",
	"<+05>-5",
	"KST-9",
	"CST-8",
	"<+08>-8",
	"<+11>-11",
	"CST-8",
	"<+05>-5",
	"<+04>-4",
	"<+0330>-3:30",
	"<+06>-6",
	"JST-9",
	"<+07>-7",
	"<+08>-8",
	"<+06>-6",
	"<+10>-10",
	"<+10>-10",
	"<+09>-9",
	"<+0630>-6:30",
	"<+05>-5",
	"<+04>-4",
	"<-01>1<+00>,M3.5.0/0,M10.5.0/1",
	"AST4ADT,M3.2.0,M11.1.0",
	"WET0WEST,M3.5.0/1,M10.5.0",
	"<-01>1",
	"WET0WEST,M3.5.0/1,M10.5.0",
	"WET0WEST,M3.5.0/1,M10.5.0",
	"<-02>2",
	"<-03>3",
	"ACST-9:30ACDT,M10.1.0,M4.1.0/3",
	"AEST-10",
	"ACST-9:30ACDT,M10.1.0,M4.1.0/3",
	"ACST-9:30",
	"<+0845>-8:45",
	"AEST-10AEDT,M10.1.0,M4.1.0/3",
	"AEST-10",
	"<+1030>-10:30<+11>-11,M10.1.0,M4.1.0",
	"AEST-10AEDT,M10.1.0,M4.1.0/3",
	"AWST-8",
	"AEST-10AEDT,M10.1.0,M4.1.0/3",
	"CET-1CEST,M3.5.0,M10.5.0/3",
	"<+04>-4",
	"EET-2EEST,M3.5.0/3,M10.5.0/4",
	"CET-1CEST,M3.5.0,M10.5.0/3",
	"CET-1CEST,M3.5.0,M10.5.0/3",
	"CET-1CEST,M3.5.0,M10.5.0/3",
	"EET-2EEST,M3.5.0/3,M10.5.0/4",
	"CET-1CEST,M3.5.0,M10.5.0/3",
	"EET-2EEST,M3.5.0/3,M10.5.0/4",
	"IST-1GMT0,M10.5.0,M3.5.0/1",
	"CET-1CEST,M3.5.0,M10.5.0/3",
	"EET-2EEST,M3.5.0/3,M10.5.0/4",
	"<+03>-3",
	"EET-2",
	"MSK-3",
	"EET-2EEST,M3.5.0/3,M10.5.0/4",
	"WET0WEST,M3.5.0/1,M10.5.0",
	"GMT0BST,M3.5.0/1,M10.5.0",
	"CET-1CEST,M3.5.0,M10.5.0/3",
	"CET-1CEST,M3.5.0,M10.5.0/3",
	"<+03>-3",
	"MSK-3",
	"CET-1CEST,M3.5.0,M10.5.0/3",
	"CET-1CEST,M3.5.0,M10.5.0/3",
	"EET-2EEST,M3.5.0/3,M10.5.0/4",
	"CET-1CEST,M3.5.0,M10.5.0/3",
	"<+04>-4",
	"<+04>-4",
	"MSK-3",
	"EET-2EEST,M3.5.0/3,M10.5.0/4",
	"EET-2EEST,M3.5.0/3,M10.5.0/4",
	"CET-1CEST,M3.5.0,M10.5.0/3",
	"<+04>-4",
	"CET-1CEST,M3.5.0,M10.5.0/3",
	"EET-2EEST,M3.5.0/3,M10.5.0/4",
	"MSK-3",
	"CET-1CEST,M3.5.0,M10.5.0/3",
	"CET-1CEST,M3.5.0,M10.5.0/3",
	"<+06>-6",
	"<+05>-5",
	"<+04>-4",
	"<+13>-13",
	"NZST-12NZDT,M9.5.0,M4.1.0/3",
	"<+11>-11",
	"<+1245>-12:45<+1345>,M9.5.0/2:45,M4.1.0/3:45",
	"<-06>6<-05>,M9.1.6/22,M4.1.6/22",
	"<+11>-11",
	"<+13>-13",
	"<+12>-12",
	"<-06>6",
	"<-09>9",
	"<+11>-11",
	"ChST-10",
	"HST10",
	"<+13>-13",
	"<+14>-14",
	"<+11>-11",
	"<+12>-12",
	"<-0930>9:30",
	"<+12>-12",
	"<-11>11",
	"<+11>-11<+12>,M10.1.0,M4.1.0/3",
	"<+11>-11",
	"SST11",
	"<+09>-9",
	"<-08>8",
	"<+10>-10",
	"<-10>10",
	"<-10>10",
	"<+12>-12",
	"<+13>-13",
	NULL,
};

const char *rcd_zone_posix(const char *name)
{
	for (int i = 0; name && rcd_zone_names[i]; i++) {
		if (strcmp(name, rcd_zone_names[i]) == 0)
			return zone_posix[i];
	}
	return NULL;
}

/*
 * The reverse, and only ever a fallback. Many names share a POSIX string --
 * Vancouver, Los_Angeles and Tijuana are all PST8PDT -- so this can only
 * return the first match, which would report a zone the operator did not pick.
 * The name they did pick is in /etc/timezone, and that is what the getter
 * reads. This covers a hand-written /etc/TZ with no matching name beside it.
 */
static const char *zone_name_for_posix(const char *posix)
{
	for (int i = 0; posix && zone_posix[i]; i++) {
		if (strcmp(posix, zone_posix[i]) == 0)
			return rcd_zone_names[i];
	}
	return NULL;
}

/* ------------------------------------------------------------------ */
/* Files                                                               */
/* ------------------------------------------------------------------ */

/* First line of a file, newline stripped. Empty string if unreadable. */
static void read_line(const char *path, char *out, size_t outsz)
{
	out[0] = '\0';

	FILE *f = fopen(path, "r");
	if (!f)
		return;
	if (fgets(out, (int)outsz, f)) {
		size_t n = strlen(out);
		while (n > 0 && (out[n - 1] == '\n' || out[n - 1] == '\r'))
			out[--n] = '\0';
	}
	fclose(f);
}

/*
 * Write via a temporary and rename, so a power cut during the write leaves the
 * old file rather than a truncated one. /etc is an overlay over NOR here, and
 * a half-written /etc/TZ is a camera that will not boot with a clock.
 */
static int write_file(const char *path, const char *content)
{
	char tmp[160];
	snprintf(tmp, sizeof(tmp), "%s.tmp", path);

	FILE *f = fopen(tmp, "w");
	if (!f) {
		RSS_WARN("system: cannot write %s: %s", tmp, strerror(errno));
		return -1;
	}
	/* rcd runs with no umask, so a new file would otherwise land
	 * world-writable. These are read by everything and written by one
	 * daemon, which is what 0644 says. */
	if (fchmod(fileno(f), 0644) != 0)
		RSS_WARN("system: cannot set the mode on %s: %s", tmp, strerror(errno));
	bool ok = fputs(content, f) >= 0;
	if (fclose(f) != 0)
		ok = false;
	if (!ok) {
		unlink(tmp);
		return -1;
	}

	if (rename(tmp, path) != 0) {
		RSS_WARN("system: cannot replace %s: %s", path, strerror(errno));
		unlink(tmp);
		return -1;
	}
	return 0;
}

/* ------------------------------------------------------------------ */
/* Timezone                                                            */
/* ------------------------------------------------------------------ */

static int tz_get(char *out, size_t outsz)
{
	char rule[128];
	read_line(PATH_TZ, rule, sizeof(rule));
	if (!rule[0])
		return -1;

	/*
	 * The name that was chosen, from /etc/timezone, checked against the
	 * table -- so the control reads back the zone the operator picked
	 * rather than whichever one happens to share its rule.
	 */
	char name[128];
	read_line(PATH_TIMEZONE, name, sizeof(name));

	const char *posix = name[0] ? rcd_zone_posix(name) : NULL;
	const char *report = (posix && strcmp(posix, rule) == 0) ? name : zone_name_for_posix(rule);

	/*
	 * A hand-written /etc/TZ that matches no name at all is reported as
	 * nothing rather than as some zone: the value has to be one of the
	 * choices for a client to render it, and inventing one would put a
	 * zone in the form that nobody selected.
	 */
	if (!report)
		return -1;

	rss_strlcpy(out, report, outsz);
	return 0;
}

static int tz_set(const char *name)
{
	const char *posix = rcd_zone_posix(name);
	if (!posix)
		return -1; /* unreachable: the enum was checked against this list */

	/*
	 * The name first and the rule second, because a reader landing between
	 * the two writes reads both files. In this order it sees the old rule
	 * beside a name that no longer matches it, rejects the name, and
	 * reports the old zone -- which is true until the second write lands.
	 * The other order reports the new rule under whichever name happens to
	 * share it, which is a zone nobody chose.
	 */
	char buf[160];
	snprintf(buf, sizeof(buf), "%s\n", name);
	write_file(PATH_TIMEZONE, buf);

	snprintf(buf, sizeof(buf), "%s\n", posix);
	if (write_file(PATH_TZ, buf) != 0)
		return -1;

	RSS_INFO("system: timezone %s (%s) -- takes effect on reboot", name, posix);
	return 0;
}

const rcd_provider_t rcd_provider_timezone = {tz_get, tz_set};

/* ------------------------------------------------------------------ */
/* NTP server                                                          */
/* ------------------------------------------------------------------ */

static int ntp_get(char *out, size_t outsz)
{
	/* First `server` line; the file is ours to write but not ours to
	 * assume -- an image or an operator may have left several. */
	FILE *f = fopen(PATH_NTP, "r");
	if (!f)
		return -1;

	int ret = -1;
	char line[256];
	while (fgets(line, sizeof(line), f)) {
		char host[128];
		if (sscanf(line, " server %127s", host) == 1) {
			rss_strlcpy(out, host, outsz);
			ret = 0;
			break;
		}
	}
	fclose(f);
	return ret;
}

static int ntp_set(const char *host)
{
	/*
	 * One server, replacing the pool the image ships with. `iburst` is
	 * kept because the first sync is the one that matters on a camera
	 * whose clock starts at the image build date.
	 */
	char buf[192];
	snprintf(buf, sizeof(buf), "server %s iburst\n", host);
	if (write_file(PATH_NTP, buf) != 0)
		return -1;

	/*
	 * Unlike the timezone this applies now: ntpd holds no state worth
	 * preserving and nothing else depends on it being up, which is why
	 * this key is a live one and the timezone is not.
	 *
	 * A build with no ntpd is not a failure. The file is written either
	 * way, and whatever reads it next gets the new server.
	 */
	if (access(PATH_NTPD, X_OK) == 0) {
		int rc = system(PATH_NTPD " restart >/dev/null 2>&1");
		RSS_INFO("system: ntp server %s (ntpd restart %s)", host,
			 rc == 0 ? "ok" : "failed -- will apply at reboot");
	} else {
		RSS_INFO("system: ntp server %s (no ntpd here)", host);
	}
	return 0;
}

const rcd_provider_t rcd_provider_ntp_server = {ntp_get, ntp_set};

/* ------------------------------------------------------------------ */
/* Hostname                                                            */
/* ------------------------------------------------------------------ */

/*
 * The camera's name, which is how it is found on the LAN: mdnsd answers to
 * <name>.local and udhcpc offers the same string to the DHCP server, so this
 * is an address by another route and is guarded accordingly -- rcd_guard.h.
 *
 * /etc/hostname is the store. The packaged copy underneath is left alone by
 * writing through the overlay, which is the only way /etc is writable here,
 * and matters because sysupgrade reads the SoC out of the hostname shipped in
 * the image it is about to flash.
 */

static int hostname_get(char *out, size_t outsz)
{
	char name[128];
	read_line(PATH_HOSTNAME, name, sizeof(name));

	/* The file is what survives a reboot, so it is the answer whenever it
	 * has one. The kernel's copy is the fallback for an image that carries
	 * no such file at all. */
	if (!name[0] && gethostname(name, sizeof(name)) != 0)
		return -1;
	if (!name[0])
		return -1;

	rss_strlcpy(out, name, outsz);
	return 0;
}

/*
 * Buildroot writes the hostname into /etc/hosts as well, as the 127.0.1.1
 * entry that lets the machine resolve its own name. Renaming the host without
 * it leaves that line pointing at a name nothing answers to, and everything
 * that resolves its own hostname -- syslog, and anything binding by name --
 * waits for a lookup that fails.
 *
 * Only that line is rewritten, and only its second field. A hosts file with no
 * such line is left as it is rather than given one: this repairs a convention
 * the image already follows, it does not impose it.
 */
static void hosts_rename(const char *name)
{
	int len = 0;
	char *text = rss_read_file(PATH_HOSTS, &len);
	if (!text)
		return;

	/* Bounded because the whole file is rebuilt in memory. Anything this
	 * size is not the two-line file this knows how to edit. */
	if (len > 8192) {
		free(text);
		RSS_WARN("system: %s is too large to rewrite; the 127.0.1.1 name is unchanged",
			 PATH_HOSTS);
		return;
	}

	char *out = calloc(1, (size_t)len + strlen(name) + 64);
	if (!out) {
		free(text);
		return;
	}

	bool touched = false;
	size_t used = 0;
	char *save = NULL;
	for (char *line = strtok_r(text, "\n", &save); line; line = strtok_r(NULL, "\n", &save)) {
		char addr[64] = "";
		if (!touched && sscanf(line, "%63s", addr) == 1 && strcmp(addr, "127.0.1.1") == 0) {
			used += (size_t)sprintf(out + used, "127.0.1.1\t%s\n", name);
			touched = true;
			continue;
		}
		used += (size_t)sprintf(out + used, "%s\n", line);
	}
	free(text);

	if (touched)
		write_file(PATH_HOSTS, out);
	free(out);
}

static int hostname_set(const char *name)
{
	char buf[128];
	snprintf(buf, sizeof(buf), "%s\n", name);
	if (write_file(PATH_HOSTNAME, buf) != 0)
		return -1;

	hosts_rename(name);

	/*
	 * The running kernel, so the name is right for everything that asks
	 * from here on without waiting for a reboot. A kernel that refuses --
	 * a test in a namespace without CAP_SYS_ADMIN is the case that turns
	 * up -- has not lost the setting: the file is written, and inittab
	 * applies it on the next boot.
	 */
	if (sethostname(name, strlen(name)) != 0)
		RSS_WARN("system: hostname stored, but the kernel kept the old name: %s",
			 strerror(errno));

	/*
	 * mdnsd reads the hostname once, at startup, and re-reads it on
	 * SIGHUP -- which is what the init script's `reload` sends. Without
	 * this the camera keeps answering to its old <name>.local and the new
	 * name resolves nowhere, which is precisely the condition this key is
	 * guarded against.
	 *
	 * Through the init script rather than a signal of our own: how a
	 * service is poked belongs in one place, and that place already
	 * exists.
	 */
	if (access(PATH_MDNSD, X_OK) == 0) {
		int rc = system(PATH_MDNSD " reload >/dev/null 2>&1");
		RSS_INFO("system: hostname %s (mdnsd reload %s)", name, rc == 0 ? "ok" : "failed");
	} else {
		RSS_INFO("system: hostname %s", name);
	}

	/* The DHCP lease still carries the old name until the interface next
	 * comes up; nothing here forces a renew, because dropping the link is
	 * a bigger interruption than the stale lease it would fix. */
	return 0;
}

const rcd_provider_t rcd_provider_hostname = {hostname_get, hostname_set};
